How far are these research reactors?

In [7]:
%%shell
pip install googledrivedownloader
pip install geopy
pip install geopandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: googledrivedownloader in /usr/local/lib/python3.8/dist-packages (0.4)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: geopy in /usr/local/lib/python3.8/dist-packages (1.17.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /usr/local/lib/python3.8/dist-packages (from geopy) (1.52)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: geopandas in /usr/local/lib/python3.8/dist-packages (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from geopandas) (21.3)
Requirement already satisfied: pyproj>=2.6.1.post1 in /usr/local/lib/python3.8/dist-packages (from geopandas) (3.4.0)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from geopandas) (1.3.5)
Requirement already satisfied: shapely>=1.7 in /usr/local/lib/python3.8/dist-packages (from geopandas) (1.8.5.post1)
Requirement already satisfied: fiona>=1.8 in /usr/local/lib/python3.8/dist-packages (from geopandas) (1.8.22)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Requirement already satisfied: munch in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (57.4.0)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (0.7.2)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (22.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (2022.9.24)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.8/dist-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.0->geopandas) (2022.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.0->geopandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.0->geopandas) (1.21.6)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->geopandas) (3.0.9)

In [1]:
from google_drive_downloader import GoogleDriveDownloader as gdd
import pandas as pd 
import numpy as np
def download_file_g_drive_url(url, file_path, unzip):
  file_id = url[url.index("/d/") + 3: -1*len("/view?usp=sharing")]
  gdd.download_file_from_google_drive(file_id, file_path, unzip)
def df_from_url(url):
  path = "/content/new_file.txt"
  download_file_g_drive_url(url, path, False)
  return pd.read_csv(path)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: googledrivedownloader in /usr/local/lib/python3.8/dist-packages (0.4)

Data source: https://nucleus.iaea.org/rrdb/#/home

In [27]:
url = "https://drive.google.com/file/d/125DiSUbUC5OQDKNOh_xYfUH4Vql_a8v7/view?usp=sharing"
df = df_from_url(url)
df = df.iloc[2:,:]
df.columns = df.iloc[0,:]
df = df.iloc[1:,:]
df

2,Facility Name,Country,City,Type,Thermal Power,Status,First Criticality Date
3,NIST,United States of America,"Gaithersburg, Maryland",HEAVY WATER,20000,OPERATIONAL,1967-12-07T00:00:00
4,ATR,United States of America,Idaho Falls,TANK,250000,OPERATIONAL,1967-07-02T00:00:00
5,OSURR Ohio State Univ.,United States of America,"Columbus, OH",POOL,500,OPERATIONAL,1961-03-16T00:00:00
6,MURR Univ. Missouri-Columbia,United States of America,"Columbia, MO",TANK IN POOL,10000,OPERATIONAL,1966-10-13T00:00:00
7,UFTR Univ. Florida,United States of America,"Gainesville, FL",ARGONAUT,100,OPERATIONAL,1959-05-28T00:00:00
8,Planet,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,0,OPERATIONAL,1950-01-01T00:00:00
9,White Sands Fast Burst Reactor,United States of America,"Las Cruces, NM",FAST BURST,10000,OPERATIONAL,1964-07-01T00:00:00
10,TREAT,United States of America,"Idaho Falls, ID","GRAPHITE, PULSE",80,OPERATIONAL,1959-02-23T00:00:00
11,NRAD,United States of America,"Idaho Falls, ID",TRIGA MARK II,250,OPERATIONAL,1977-10-12T00:00:00
12,"OSTR, Oregon State Univ.",United States of America,"Corvallis, OR",TRIGA MARK II,1100,OPERATIONAL,1967-03-08T00:00:00
13,Sandia SPR CX,United States of America,"Albuquerque, NM",CRIT ASSEMBLY,0.001,OPERATIONAL,1989-10-24T00:00:00
14,AGN-201 Univ. New Mexico,United States of America,"Albuquerque, NM",HOMOG (S),0.005,OPERATIONAL,1966-10-01T00:00:00
15,MUTR Univ. Maryland,United States of America,"College Park, MD",TRIGA MODIFIED,250,OPERATIONAL,1960-12-01T00:00:00
16,NSCR Texas A&M Univ.,United States of America,"College Station, TX",TRIGA CONV,1000,OPERATIONAL,1962-01-01T00:00:00
17,AGN-201 Texas A&M Univ.,United States of America,"College Station, TX",HOMOG (S),0.005,OPERATIONAL,1957-01-01T00:00:00
18,UC Irvine TRIGA,United States of America,"Irvine, CA",TRIGA MARK I,250,OPERATIONAL,1969-11-25T00:00:00
19,AFRRI TRIGA,United States of America,"Bethesda, MD",TRIGA MARK F,1000,OPERATIONAL,1962-01-01T00:00:00
20,GSTR US Geological Survey,United States of America,Denver,TRIGA MARK I,1000,OPERATIONAL,1969-02-26T00:00:00
21,RINSC Rhode Island NSC,United States of America,"Narragansett, RI",POOL,2000,OPERATIONAL,1964-07-28T00:00:00
22,PUR-1 Purdue Univ.,United States of America,"West Lafayette, IN",POOL,1,OPERATIONAL,1962-01-01T00:00:00
23,RRR Reed College,United States of America,"Portland, OR",TRIGA MARK I,250,OPERATIONAL,1968-07-02T00:00:00
24,WRCF Rensselaer Polytechnic,United States of America,"Schenectady, NY",CRIT ASSEMBLY,0.1,OPERATIONAL,1956-08-26T00:00:00
25,PSBR Penn St. Unv.,United States of America,"State College, PA",TRIGA MARK CONV,1000,OPERATIONAL,1955-08-15T00:00:00
26,Bettis TRX CA,United States of America,"West Mifflin, PA",CRIT ASSEMBLY,0.01,OPERATIONAL,1953-01-01T00:00:00
27,TACS Training Assembly Crit Safety,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,0,OPERATIONAL,1979-08-30T00:00:00
28,KSU TRIGA Mark II,United States of America,"Manhattan, KN",TRIGA MARK II,250,OPERATIONAL,1962-10-16T00:00:00
29,TRIGA II Univ. Texas,United States of America,"Austin, TX",TRIGA MARK II,1100,OPERATIONAL,1992-03-12T00:00:00
30,UC Davis/McClellan TRIGA,United States of America,"Sacramento, CA",TRIGA MARK II,2000,OPERATIONAL,1990-01-20T00:00:00
31,MITR-II Masschusetts Inst. of Tech.,United States of America,Boston,TANK,6000,OPERATIONAL,1958-07-21T00:00:00
32,MTS-626,United States of America,"Charleston, SC",PWR PROPULSION,78000,OPERATIONAL,1963-04-27T00:00:00
33,MTS-635,United States of America,"Charleston, SC",PWR PROPULSION,78000,OPERATIONAL,1964-12-20T00:00:00
34,Dow TRIGA,United States of America,"Midland, MI",TRIGA MARK I,300,OPERATIONAL,1967-07-06T00:00:00
35,AGN-201 Idaho St. Univ.,United States of America,"Pocatello, ID",HOMOG (S),0.005,OPERATIONAL,1967-01-01T00:00:00
36,ISSA Inherently Safe Subcrit,United States of America,"Livermore, CA",SUBCRIT,0,OPERATIONAL,2012-09-13T00:00:00
37,MARF,United States of America,"Ballston Spa, NY",PRESSURIZED,0,OPERATIONAL,1976-01-01T00:00:00
38,S8G Submarine Prototype,United States of America,"Ballston Spa, NY",PWR PROPULSION,0,OPERATIONAL,1979-01-01T00:00:00
39,ACRR Annular Core RR,United States of America,"Albuquerque, NM",TRIGA MODIFIED,2400,OPERATIONAL,1967-06-01T00:00:00
40,WSUR Washington State Univ.,United States of America,"Pullman, WA",TRIGA CONV,1000,OPERATIONAL,1961-03-07T00:00:00
41,Flattop,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,0.1,OPERATIONAL,1957-01-01T00:00:00
42,ARRR,United States of America,"San Ramon, CA",TRIGA CONV,250,OPERATIONAL,1964-07-09T00:00:00
43,UWNR Univ. Wisconsin,United States of America,"Madison, WI",TRIGA CONV,1000,OPERATIONAL,1961-03-26T00:00:00
44,TRIGA Univ. Utah,United States of America,"Salt Lake City, UT",TRIGA MARK I,100,OPERATIONAL,1975-10-25T00:00:00
45,MSTR Missouri Univ. of Science & Tech.,United States of America,"Rolla, MO","POOL, MTR",200,OPERATIONAL,1961-12-11T00:00:00
46,UMLR Univ. Mass. Lowell,United States of America,"Lowell, MA",POOL,1000,OPERATIONAL,1975-01-02T00:00:00
47,HFIR,United States of America,"Oak Ridge, TN",TANK,85000,OPERATIONAL,1965-08-01T00:00:00
48,PULSTAR North Carolina State Univ.,United States of America,Raleigh,"POOL, PULSTAR",1000,OPERATIONAL,1972-01-01T00:00:00
49,Comet,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,0.5,OPERATIONAL,1952-01-01T00:00:00
50,Godiva IV,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,1,OPERATIONAL,1967-01-01T00:00:00
51,ATRC,United States of America,"Idaho Falls, ID",POOL,5,OPERATIONAL,1964-05-19T00:00:00
52,NTR General Electric,United States of America,"Pleasanton, CA",GRAPHITE,100,OPERATIONAL,1957-11-15T00:00:00

In [13]:
!pip install --upgrade plotly

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: plotly in /usr/local/lib/python3.8/dist-packages (5.5.0)
Collecting plotly
  Downloading plotly-5.11.0-py2.py3-none-any.whl (15.3 MB)
     |████████████████████████████████| 15.3 MB 9.3 MB/s
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from plotly) (8.1.0)
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.5.0
    Uninstalling plotly-5.5.0:
      Successfully uninstalled plotly-5.5.0
Successfully installed plotly-5.11.0

In [8]:
# Import the required library
from geopy.geocoders import Nominatim

# Initialize Nominatim API
geolocator = Nominatim(user_agent="MyApp")

location = geolocator.geocode("Hyderabad")

print("The latitude of the location is: ", location.latitude)
print("The longitude of the location is: ", location.longitude)

The latitude of the location is:  17.360589
The longitude of the location is:  78.4740613

The following cell takes about 30 seconds

In [29]:
city_names = [x.split(",")[0] if "," in x   else x for x in df["City"]]
locations = [geolocator.geocode(city) for city in city_names]

In [36]:
df["Latitude"] = [location.latitude for location in locations]
df["Longitude"] = [location.longitude for location in locations]
df.rename(columns = {'Thermal Power':'Thermal Power (kw)'}, inplace = True)
df

2,Facility Name,Country,City,Type,Thermal Power (kw),Status,First Criticality Date,Latitude,Longitude
3,NIST,United States of America,"Gaithersburg, Maryland",HEAVY WATER,20000,OPERATIONAL,1967-12-07T00:00:00,39.139919,-77.192921
4,ATR,United States of America,Idaho Falls,TANK,250000,OPERATIONAL,1967-07-02T00:00:00,43.488791,-112.036280
5,OSURR Ohio State Univ.,United States of America,"Columbus, OH",POOL,500,OPERATIONAL,1961-03-16T00:00:00,39.962260,-83.000707
6,MURR Univ. Missouri-Columbia,United States of America,"Columbia, MO",TANK IN POOL,10000,OPERATIONAL,1966-10-13T00:00:00,4.099917,-72.908813
7,UFTR Univ. Florida,United States of America,"Gainesville, FL",ARGONAUT,100,OPERATIONAL,1959-05-28T00:00:00,29.651968,-82.324985
8,Planet,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,0,OPERATIONAL,1950-01-01T00:00:00,36.167256,-115.148516
9,White Sands Fast Burst Reactor,United States of America,"Las Cruces, NM",FAST BURST,10000,OPERATIONAL,1964-07-01T00:00:00,32.314035,-106.779807
10,TREAT,United States of America,"Idaho Falls, ID","GRAPHITE, PULSE",80,OPERATIONAL,1959-02-23T00:00:00,43.488791,-112.036280
11,NRAD,United States of America,"Idaho Falls, ID",TRIGA MARK II,250,OPERATIONAL,1977-10-12T00:00:00,43.488791,-112.036280
12,"OSTR, Oregon State Univ.",United States of America,"Corvallis, OR",TRIGA MARK II,1100,OPERATIONAL,1967-03-08T00:00:00,44.564566,-123.262044
13,Sandia SPR CX,United States of America,"Albuquerque, NM",CRIT ASSEMBLY,0.001,OPERATIONAL,1989-10-24T00:00:00,35.084103,-106.650985
14,AGN-201 Univ. New Mexico,United States of America,"Albuquerque, NM",HOMOG (S),0.005,OPERATIONAL,1966-10-01T00:00:00,35.084103,-106.650985
15,MUTR Univ. Maryland,United States of America,"College Park, MD",TRIGA MODIFIED,250,OPERATIONAL,1960-12-01T00:00:00,38.990412,-76.943859
16,NSCR Texas A&M Univ.,United States of America,"College Station, TX",TRIGA CONV,1000,OPERATIONAL,1962-01-01T00:00:00,30.595529,-96.307104
17,AGN-201 Texas A&M Univ.,United States of America,"College Station, TX",HOMOG (S),0.005,OPERATIONAL,1957-01-01T00:00:00,30.595529,-96.307104
18,UC Irvine TRIGA,United States of America,"Irvine, CA",TRIGA MARK I,250,OPERATIONAL,1969-11-25T00:00:00,33.685697,-117.825982
19,AFRRI TRIGA,United States of America,"Bethesda, MD",TRIGA MARK F,1000,OPERATIONAL,1962-01-01T00:00:00,38.981273,-77.123359
20,GSTR US Geological Survey,United States of America,Denver,TRIGA MARK I,1000,OPERATIONAL,1969-02-26T00:00:00,39.739236,-104.984862
21,RINSC Rhode Island NSC,United States of America,"Narragansett, RI",POOL,2000,OPERATIONAL,1964-07-28T00:00:00,41.450102,-71.449500
22,PUR-1 Purdue Univ.,United States of America,"West Lafayette, IN",POOL,1,OPERATIONAL,1962-01-01T00:00:00,40.425869,-86.908066
23,RRR Reed College,United States of America,"Portland, OR",TRIGA MARK I,250,OPERATIONAL,1968-07-02T00:00:00,45.520247,-122.674194
24,WRCF Rensselaer Polytechnic,United States of America,"Schenectady, NY",CRIT ASSEMBLY,0.1,OPERATIONAL,1956-08-26T00:00:00,42.814243,-73.939569
25,PSBR Penn St. Unv.,United States of America,"State College, PA",TRIGA MARK CONV,1000,OPERATIONAL,1955-08-15T00:00:00,40.794450,-77.861639
26,Bettis TRX CA,United States of America,"West Mifflin, PA",CRIT ASSEMBLY,0.01,OPERATIONAL,1953-01-01T00:00:00,40.363403,-79.866438
27,TACS Training Assembly Crit Safety,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,0,OPERATIONAL,1979-08-30T00:00:00,36.167256,-115.148516
28,KSU TRIGA Mark II,United States of America,"Manhattan, KN",TRIGA MARK II,250,OPERATIONAL,1962-10-16T00:00:00,40.789624,-73.959894
29,TRIGA II Univ. Texas,United States of America,"Austin, TX",TRIGA MARK II,1100,OPERATIONAL,1992-03-12T00:00:00,30.271129,-97.743700
30,UC Davis/McClellan TRIGA,United States of America,"Sacramento, CA",TRIGA MARK II,2000,OPERATIONAL,1990-01-20T00:00:00,38.581061,-121.493895
31,MITR-II Masschusetts Inst. of Tech.,United States of America,Boston,TANK,6000,OPERATIONAL,1958-07-21T00:00:00,42.355433,-71.060511
32,MTS-626,United States of America,"Charleston, SC",PWR PROPULSION,78000,OPERATIONAL,1963-04-27T00:00:00,32.787601,-79.940273
33,MTS-635,United States of America,"Charleston, SC",PWR PROPULSION,78000,OPERATIONAL,1964-12-20T00:00:00,32.787601,-79.940273
34,Dow TRIGA,United States of America,"Midland, MI",TRIGA MARK I,300,OPERATIONAL,1967-07-06T00:00:00,31.997366,-102.077948
35,AGN-201 Idaho St. Univ.,United States of America,"Pocatello, ID",HOMOG (S),0.005,OPERATIONAL,1967-01-01T00:00:00,42.862029,-112.450627
36,ISSA Inherently Safe Subcrit,United States of America,"Livermore, CA",SUBCRIT,0,OPERATIONAL,2012-09-13T00:00:00,37.682058,-121.768053
37,MARF,United States of America,"Ballston Spa, NY",PRESSURIZED,0,OPERATIONAL,1976-01-01T00:00:00,43.000909,-73.849011
38,S8G Submarine Prototype,United States of America,"Ballston Spa, NY",PWR PROPULSION,0,OPERATIONAL,1979-01-01T00:00:00,43.000909,-73.849011
39,ACRR Annular Core RR,United States of America,"Albuquerque, NM",TRIGA MODIFIED,2400,OPERATIONAL,1967-06-01T00:00:00,35.084103,-106.650985
40,WSUR Washington State Univ.,United States of America,"Pullman, WA",TRIGA CONV,1000,OPERATIONAL,1961-03-07T00:00:00,46.730427,-117.173895
41,Flattop,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,0.1,OPERATIONAL,1957-01-01T00:00:00,36.167256,-115.148516
42,ARRR,United States of America,"San Ramon, CA",TRIGA CONV,250,OPERATIONAL,1964-07-09T00:00:00,41.725337,1.363189
43,UWNR Univ. Wisconsin,United States of America,"Madison, WI",TRIGA CONV,1000,OPERATIONAL,1961-03-26T00:00:00,43.074761,-89.383761
44,TRIGA Univ. Utah,United States of America,"Salt Lake City, UT",TRIGA MARK I,100,OPERATIONAL,1975-10-25T00:00:00,40.759620,-111.886798
45,MSTR Missouri Univ. of Science & Tech.,United States of America,"Rolla, MO","POOL, MTR",200,OPERATIONAL,1961-12-11T00:00:00,13.848500,77.098513
46,UMLR Univ. Mass. Lowell,United States of America,"Lowell, MA",POOL,1000,OPERATIONAL,1975-01-02T00:00:00,42.633425,-71.316172
47,HFIR,United States of America,"Oak Ridge, TN",TANK,85000,OPERATIONAL,1965-08-01T00:00:00,36.010356,-84.269645
48,PULSTAR North Carolina State Univ.,United States of America,Raleigh,"POOL, PULSTAR",1000,OPERATIONAL,1972-01-01T00:00:00,35.780398,-78.639099
49,Comet,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,0.5,OPERATIONAL,1952-01-01T00:00:00,36.167256,-115.148516
50,Godiva IV,United States of America,"Las Vegas, NV",CRIT ASSEMBLY,1,OPERATIONAL,1967-01-01T00:00:00,36.167256,-115.148516
51,ATRC,United States of America,"Idaho Falls, ID",POOL,5,OPERATIONAL,1964-05-19T00:00:00,43.488791,-112.036280
52,NTR General Electric,United States of America,"Pleasanton, CA",GRAPHITE,100,OPERATIONAL,1957-11-15T00:00:00,37.662431,-121.874679

In [39]:
import plotly.express as px
fig = px.scatter_mapbox(
    df,
    lat="Latitude",
    lon="Longitude",
    hover_name="City",
    hover_data=[x for x in df.columns],
    color_discrete_sequence=["fuchsia"],
    zoom=3,
    height=300,
)
fig.update_layout(mapbox_style="open-street-map")
fig.update_layout(margin={"r": 0, "t": 0, "l": 0, "b": 0})
fig.update_layout(mapbox_bounds={"west": -180, "east": -50, "south": 20, "north": 90})
fig

In [40]:
fig.write_html("reactor_map.html")